language: rust
sudo: false

env:
  - PKGS='-p tower-web -p tower-web-macros'

matrix:
  include:
    - rust: stable
    - rust: nightly
    # minimum rustc version
    - rust: 1.34.0
      script: cargo build

  allow_failures:
    - rust: nightly

script:
  - cargo check --no-default-features $PKGS
  - cargo test --lib --no-default-features $PKGS
  - cargo test --tests --no-default-features $PKGS
  - cargo test $PKGS
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then cd test_suite && cargo test; fi

notifications:
  email:
    on_success: never
