[package]
name = "tower-web"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[workspace]

members = [
  "./",
  "tower-web-macros",
]

[dependencies]
bytes = "0.4.7"
futures = "0.1.21"
http = "0.1.7"
hyper = "0.12.1"
log = "0.4.1"
tokio = "0.1.6"
tokio-fs = "0.1.2"
tokio-io = "0.1.7"
tower-service = { git = "https://github.com/tower-rs/tower" }

# Parsing params
atoi = "0.2.3"
chrono = "0.4.4"

# Serializing responses, deserializing requests
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
serde_plain = "0.3.0"
serde_urlencoded = "0.5.1"

# Code gen
tower-web-macros = { version = "0.1.0", path = "tower-web-macros" }
proc-macro-hack = "0.4.0"

[dev-dependencies]
env_logger = "0.5.12"
